[feature] Can restrict some mobile prefixes #160
openwisp/openwisp-radius pull request #170
Opened 2020-09-28 20:31 UTC by NoumbissiValere

Closes #160

2020-09-28 20:34 UTC, TravisBuddy commented
Hey @NoumbissiValere,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-radius&#x2F;builds&#x2F;731086162">View build log</a>

###### TravisBuddy Request Identifier: 131559c0-01ca-11eb-9be6-0d9634a5fbe7

2020-09-28 20:37 UTC, TravisBuddy commented
Hey @NoumbissiValere,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-radius&#x2F;builds&#x2F;731086748">View build log</a>

###### TravisBuddy Request Identifier: 5e5a2640-01ca-11eb-9be6-0d9634a5fbe7

2020-09-28 20:46 UTC, NoumbissiValere commented on requirements.txt
> +djangorestframework<3.12,>=3.11
Added this because build was failing as showed by the `travis buddy` above

2020-09-28 20:51 UTC, TravisBuddy commented
## Travis tests have failed

Hey @NoumbissiValere,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 4th Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-radius&#x2F;jobs&#x2F;731088941">View build log</a>


<details>
  <summary>
    <strong>
     .&#x2F;run-qa-checks
    </strong>
  </summary>

```
Checking documentation build status
Running Sphinx v3.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: [new config] 15 added, 0 changed, 0 removed
reading sources... [  6%] developer/contributing                                
reading sources... [ 13%] developer/freeradius                                  
reading sources... [ 20%] developer/how_to_extend                               
reading sources... [ 26%] developer/setup                                       
reading sources... [ 33%] general/goals                                         
reading sources... [ 40%] general/support                                       
reading sources... [ 46%] index                                                 
reading sources... [ 53%] user/api                                              
reading sources... [ 60%] user/enforcing_limits                                 
reading sources... [ 66%] user/generating_users                                 
reading sources... [ 73%] user/importing_users                                  
reading sources... [ 80%] user/management_commands                              
reading sources... [ 86%] user/registration                                     
reading sources... [ 93%] user/settings                                         
reading sources... [100%] user/social_login                                     

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  6%] developer/contributing                                 
writing output... [ 13%] developer/freeradius                                   
writing output... [ 20%] developer/how_to_extend                                
writing output... [ 26%] developer/setup                                        
writing output... [ 33%] general/goals                                          
writing output... [ 40%] general/support                                        
writing output... [ 46%] index                                                  
writing output... [ 53%] user/api                                               
writing output... [ 60%] user/enforcing_limits                                  
writing output... [ 66%] user/generating_users                                  
writing output... [ 73%] user/importing_users                                   
writing output... [ 80%] user/management_commands                               
writing output... [ 86%] user/registration                                      
writing output... [ 93%] user/settings                                          
writing output... [100%] user/social_login                                      

generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [ 10%] images/demo_radius.gif                                 
copying images... [ 20%] images/swagger_api.png                                 
copying images... [ 30%] images/drf_api_interface.png                           
copying images... [ 40%] images/token.png                                       
copying images... [ 50%] images/org_uuid.png                                    
copying images... [ 60%] images/download_user_credentials_button.png            
copying images... [ 70%] images/pdf_of_user_list.png                            
copying images... [ 80%] images/add_users_prefix.gif                            
copying images... [ 90%] images/add_users_csv.gif                               
copying images... [100%] images/freeradius_allowed_hosts.png                    

copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in docs/build.
SUCCESS Crawled 129 urls in 3.68 seconds
./run-qa-checks: line 19:  6523 Terminated              python -m http.server 8001 -d docs/build/ &> /dev/null

Check JavaScript Linting

./openwisp_radius/static/openwisp-radius/js/mode-switcher.js is OK.

./openwisp_radius/static/openwisp-radius/js/radcheck.js is OK.

./openwisp_radius/static/openwisp-radius/js/strategy-switcher.js is OK.

Running checks for openwisp-radius
SUCCESS: Blank endline check successful!
SUCCESS: Migration name check on "./openwisp_radius/migrations" with migrations-to-ignore: 0 successful!
Skipped 1 files
SUCCESS: Isort check successful!
All done! ✨ 🍰 ✨
116 files would be left unchanged.
SUCCESS: Black check successful!
./openwisp_radius/migrations/0016_organizationradiussettings_restricted_mobile_prefixes.py:18:89: E501 line too long (100 > 88 characters)
ERROR: Flake8 check failed!
SUCCESS: Commit message check successful!
No changes detected
SUCCESS: Migrations check successful!
travis_time:end:14b69f8a:start=1601325882449672589,finish=1601325905213692010,duration=22764019421,event=script
```

</details>


### 6th Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-radius&#x2F;jobs&#x2F;731088943">View build log</a>


<details>
  <summary>
    <strong>
     .&#x2F;run-qa-checks
    </strong>
  </summary>

```
Checking documentation build status
Running Sphinx v3.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: [new config] 15 added, 0 changed, 0 removed
reading sources... [100%] user/social_login                                     
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] user/social_login                                      
generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [100%] images/freeradius_allowed_hosts.png                    
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in docs/build.
SUCCESS Crawled 129 urls in 3.67 seconds
./run-qa-checks: line 19:  6501 Terminated              python -m http.server 8001 -d docs/build/ &> /dev/null

Check JavaScript Linting

./openwisp_radius/static/openwisp-radius/js/mode-switcher.js is OK.

./openwisp_radius/static/openwisp-radius/js/radcheck.js is OK.

./openwisp_radius/static/openwisp-radius/js/strategy-switcher.js is OK.

Running checks for openwisp-radius
fatal: bad object 02959a39584d56985db13b943bc460dd122b4c35
SUCCESS: Blank endline check successful!
SUCCESS: Migration name check on "./openwisp_radius/migrations" with migrations-to-ignore: 0 successful!
Skipped 1 files
SUCCESS: Isort check successful!
All done! ✨ 🍰 ✨
116 files would be left unchanged.
SUCCESS: Black check successful!
./openwisp_radius/migrations/0016_organizationradiussettings_restricted_mobile_prefixes.py:18:89: E501 line too long (100 > 88 characters)
ERROR: Flake8 check failed!
Your commit message does not follow our commit message style guidelines:

- missing prefix in the commit short description
  Eg: "[feature/fix/change] Action performed"

Please read our guidelines at: http://openwisp.io/docs/developer/contributing.html#commit-message-style-guidelines
Checked commit message:


Merge 61307b33ec9f84c4dd4278c597c58e30ab4a357b into 41b29d94a092f2d565f071983fdce9bdac84f335


ERROR: Commit message check failed!
No changes detected
SUCCESS: [...]

2020-09-28 20:58 UTC, TravisBuddy commented
## Travis tests have failed

Hey @NoumbissiValere,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 2nd Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-radius&#x2F;jobs&#x2F;731089512">View build log</a>


<details>
  <summary>
    <strong>
     .&#x2F;run-qa-checks
    </strong>
  </summary>

```
Checking documentation build status
Running Sphinx v3.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: [new config] 15 added, 0 changed, 0 removed
reading sources... [  6%] developer/contributing                                
reading sources... [ 13%] developer/freeradius                                  
reading sources... [ 20%] developer/how_to_extend                               
reading sources... [ 26%] developer/setup                                       
reading sources... [ 33%] general/goals                                         
reading sources... [ 40%] general/support                                       
reading sources... [ 46%] index                                                 
reading sources... [ 53%] user/api                                              
reading sources... [ 60%] user/enforcing_limits                                 
reading sources... [ 66%] user/generating_users                                 
reading sources... [ 73%] user/importing_users                                  
reading sources... [ 80%] user/management_commands                              
reading sources... [ 86%] user/registration                                     
reading sources... [ 93%] user/settings                                         
reading sources... [100%] user/social_login                                     

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  6%] developer/contributing                                 
writing output... [ 13%] developer/freeradius                                   
writing output... [ 20%] developer/how_to_extend                                
writing output... [ 26%] developer/setup                                        
writing output... [ 33%] general/goals                                          
writing output... [ 40%] general/support                                        
writing output... [ 46%] index                                                  
writing output... [ 53%] user/api                                               
writing output... [ 60%] user/enforcing_limits                                  
writing output... [ 66%] user/generating_users                                  
writing output... [ 73%] user/importing_users                                   
writing output... [ 80%] user/management_commands                               
writing output... [ 86%] user/registration                                      
writing output... [ 93%] user/settings                                          
writing output... [100%] user/social_login                                      

generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [ 10%] images/demo_radius.gif                                 
copying images... [ 20%] images/swagger_api.png                                 
copying images... [ 30%] images/drf_api_interface.png                           
copying images... [ 40%] images/token.png                                       
copying images... [ 50%] images/org_uuid.png                                    
copying images... [ 60%] images/download_user_credentials_button.png            
copying images... [ 70%] images/pdf_of_user_list.png                            
copying images... [ 80%] images/add_users_prefix.gif                            
copying images... [ 90%] images/add_users_csv.gif                               
copying images... [100%] images/freeradius_allowed_hosts.png                    

copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in docs/build.

Check JavaScript Linting

./openwisp_radius/static/openwisp-radius/js/mode-switcher.js is OK.

./openwisp_radius/static/openwisp-radius/js/radcheck.js is OK.

./openwisp_radius/static/openwisp-radius/js/strategy-switcher.js is OK.

Running checks for openwisp-radius
SUCCESS: Blank endline check successful!
SUCCESS: Migration name check on "./openwisp_radius/migrations" with migrations-to-ignore: 0 successful!
Skipped 1 files
SUCCESS: Isort check successful!
All done! ✨ 🍰 ✨
116 files would be left unchanged.
SUCCESS: Black check successful!
./openwisp_radius/migrations/0016_organizationradiussettings_restricted_mobile_prefixes.py:18:89: E501 line too long (100 > 88 characters)
ERROR: Flake8 check failed!
SUCCESS: Commit message check successful!
No changes detected
SUCCESS: Migrations check successful!
travis_time:end:04087669:start=1601326202835876451,finish=1601326219482406347,duration=16646529896,event=script
```

</details>


<details>
  <summary>
    <strong>
     coverage run --source&#x3D;openwisp_radius runtests.py
    </strong>
  </summary>

```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.................../home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/django/contrib/admin/options.py:801: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'openwisp_users.models.User'> QuerySet.
  return self.paginator(queryset, per_page, orphans, allow_empty_first_page)
./home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1370: RuntimeWarning: DateTimeField RadiusAccounting.start_time received a naive datetime (2017-06-10 10:50:00) while time zone support is active.
  RuntimeWarning)
/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1370: RuntimeWarning: DateTimeField RadiusAccounting.update_time received a naive datetime (2017-03-10 11:50:00) while time zone support is active.
  RuntimeWarning)
/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1370: RuntimeWarning: DateTimeField RadiusAccounting.stop_time received a naive datetime (2017-06-10 11:50:00) while time zone support is active.
  RuntimeWarning)
......Generated a batch of users with prefix test-prefix6
Generated a batch of users with prefix test-prefix6
Generated a batch of users with prefix test-prefix6
.........................Radius token does not exist. Obtain a new radius token or provide the organization UUID and API token.
..............Radius token does not exist. Obtain a new radius token or provide the organization UUID and API token.
...WARNING:root:No corresponding user found for username: admin
.WARNING:django.request:Forbidden: /api/v1/freeradius/accounting/
.WARNING:root:No corresponding user found for username: username
....WARNING:root:No corresponding user found for username: admin
..WARNING:root:No corresponding user found for username: admin
..WARNING:django.request:Unauthorized: /api/v1/test-org/radiusbatch/189e26c5-dbe4-4b98-bb10-ad9bc4be871a/pdf/
WARNING:django.request:Forbidden: /api/v1/test-org/radiusbatch/189e26c5-dbe4-4b98-bb10-ad9bc4be871a/pdf/
WARNING:django.request:Forbidden: /api/v1/test-org/radiusbatch/189e26c5-dbe4-4b98-bb10-ad9bc4be871a/pdf/
WARNING:django.request:Forbidden: /api/v1/test-org/radiusbatch/189e26c5-dbe4-4b98-bb10-ad9bc4be871a/pdf/
WARNING:django.request:Forbidden: /api/v1/test-org/radiusbatch/189e26c5-dbe4-4b98-bb10-ad9bc4be871a/pdf/
.WARNING:django.request:Bad Request: /api/v1/radiusbatch/
.WARNING:django.reques [...]

2020-09-29 15:28 UTC, NoumbissiValere commented
@atb00ker please can you review this work in your free time? Thanks

2020-10-01 02:56 UTC, nemesisdesign requested changes
Quoting from: https://github.com/openwisp/openwisp-radius/issues/160

> Therefore we need to allow organizations to specify which international prefixes they allow.
> By default, if this is unspecified, all prefixes should be allowed.

Our need now is to specify which countries are supported, but right now you implemented a way to specify which countries are not supported, this is problematic, because the immediate need is to allow only a handful of countries, so restricting the rest of the countries would be time consuming.

We should either reverse the implementation or add another option and field (eg: `OPENWISP_RADIUS_ALLOWED_MOBILE_PREFIXES` and `allowed_mobile_prefixes`) so we can do both.

I lean in favor of keeping it simple and just switching to `OPENWISP_RADIUS_ALLOWED_MOBILE_PREFIXES` and `allowed_mobile_prefixes`.

I still have not tested it nor reviewed the rest of the code in detail, but overall looks good.

2020-10-01 03:06 UTC, NoumbissiValere commented
Ok @nemesisdesign I will revere it to allowed. Thank you for reviewing

2020-10-02 20:34 UTC, TravisBuddy commented
## Travis tests have failed

Hey @NoumbissiValere,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 2nd Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-radius&#x2F;jobs&#x2F;732377299">View build log</a>


<details>
  <summary>
    <strong>
     .&#x2F;run-qa-checks
    </strong>
  </summary>

```
Checking documentation build status
Running Sphinx v3.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: [new config] 15 added, 0 changed, 0 removed
reading sources... [100%] user/social_login                                     
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] user/social_login                                      
generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [100%] images/freeradius_allowed_hosts.png                    
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in docs/build.
SUCCESS Crawled 129 urls in 3.82 seconds
./run-qa-checks: line 19:  6552 Terminated              python -m http.server 8001 -d docs/build/ &> /dev/null

Check JavaScript Linting

./openwisp_radius/static/openwisp-radius/js/mode-switcher.js is OK.

./openwisp_radius/static/openwisp-radius/js/radcheck.js is OK.

./openwisp_radius/static/openwisp-radius/js/strategy-switcher.js is OK.

Running checks for openwisp-radius
fatal: bad object f496b2c1b4409348d1fb0bbb36d52a04f60fe181
SUCCESS: Blank endline check successful!
SUCCESS: Migration name check on "./openwisp_radius/migrations" with migrations-to-ignore: 0 successful!
Skipped 1 files
SUCCESS: Isort check successful!
All done! ✨ 🍰 ✨
116 files would be left unchanged.
SUCCESS: Black check successful!
SUCCESS: Flake8 check successful!
Your commit message does not follow our commit message style guidelines:

- missing prefix in the commit short description
  Eg: "[feature/fix/change] Action performed"

Please read our guidelines at: http://openwisp.io/docs/developer/contributing.html#commit-message-style-guidelines
Checked commit message:


Merge 439b82b261e40d59854c2e45caf55794623f2bae into 41b29d94a092f2d565f071983fdce9bdac84f335


ERROR: Commit message check failed!
No changes detected
SUCCESS: Migrations check successful!
```

</details>


###### TravisBuddy Request Identifier: bac60800-04ee-11eb-a4bc-1b94c014fd22

2020-10-02 20:41 UTC, TravisBuddy commented
## Travis tests have failed

Hey @NoumbissiValere,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 2nd Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-radius&#x2F;jobs&#x2F;732377710">View build log</a>


<details>
  <summary>
    <strong>
     .&#x2F;run-qa-checks
    </strong>
  </summary>

```
Checking documentation build status
Running Sphinx v3.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: [new config] 15 added, 0 changed, 0 removed
reading sources... [  6%] developer/contributing                                
reading sources... [ 13%] developer/freeradius                                  
reading sources... [ 20%] developer/how_to_extend                               
reading sources... [ 26%] developer/setup                                       
reading sources... [ 33%] general/goals                                         
reading sources... [ 40%] general/support                                       
reading sources... [ 46%] index                                                 
reading sources... [ 53%] user/api                                              
reading sources... [ 60%] user/enforcing_limits                                 
reading sources... [ 66%] user/generating_users                                 
reading sources... [ 73%] user/importing_users                                  
reading sources... [ 80%] user/management_commands                              
reading sources... [ 86%] user/registration                                     
reading sources... [ 93%] user/settings                                         
reading sources... [100%] user/social_login                                     

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  6%] developer/contributing                                 
writing output... [ 13%] developer/freeradius                                   
writing output... [ 20%] developer/how_to_extend                                
writing output... [ 26%] developer/setup                                        
writing output... [ 33%] general/goals                                          
writing output... [ 40%] general/support                                        
writing output... [ 46%] index                                                  
writing output... [ 53%] user/api                                               
writing output... [ 60%] user/enforcing_limits                                  
writing output... [ 66%] user/generating_users                                  
writing output... [ 73%] user/importing_users                                   
writing output... [ 80%] user/management_commands                               
writing output... [ 86%] user/registration                                      
writing output... [ 93%] user/settings                                          
writing output... [100%] user/social_login                                      

generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [ 10%] images/demo_radius.gif                                 
copying images... [ 20%] images/swagger_api.png                                 
copying images... [ 30%] images/drf_api_interface.png                           
copying images... [ 40%] images/token.png                                       
copying images... [ 50%] images/org_uuid.png                                    
copying images... [ 60%] images/download_user_credentials_button.png            
copying images... [ 70%] images/pdf_of_user_list.png                            
copying images... [ 80%] images/add_users_prefix.gif                            
copying images... [ 90%] images/add_users_csv.gif                               
copying images... [100%] images/freeradius_allowed_hosts.png                    

copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in docs/build.

Check JavaScript Linting

./openwisp_radius/static/openwisp-radius/js/mode-switcher.js is OK.

./openwisp_radius/static/openwisp-radius/js/radcheck.js is OK.

./openwisp_radius/static/openwisp-radius/js/strategy-switcher.js is OK.

Running checks for openwisp-radius
fatal: bad object 439b82b261e40d59854c2e45caf55794623f2bae
SUCCESS: Blank endline check successful!
SUCCESS: Migration name check on "./openwisp_radius/migrations" with migrations-to-ignore: 0 successful!
Skipped 1 files
SUCCESS: Isort check successful!
All done! ✨ 🍰 ✨
116 files would be left unchanged.
SUCCESS: Black check successful!
SUCCESS: Flake8 check successful!
Your commit message does not follow our commit message style guidelines:

- missing prefix in the commit short description
  Eg: "[feature/fix/change] Action performed"

Please read our guidelines at: http://openwisp.io/docs/developer/contributing.html#commit-message-style-guidelines
Checked commit message:


Merge 0de8f0c1d92d4f53b1f0d433d6b665ed4e9d28aa into 41b29d94a092f2d565f071983fdce9bdac84f335


ERROR: Commit message check failed!
No changes detected
SUCCESS: Migrations check successful!
travis_time:end:23db7b76:start=1601670739528858078,finish=1601670756410670579,duration=16881812501,event=script
```

</details>


### 6th Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-radius&#x2F;jobs&#x2F;732377714">View build log</a>


<details>
  <summary>
    <strong>
     .&#x2F;run-qa-checks
    </strong>
  </summary>

```
Checking documentation build status
Running Sphinx v3.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: [new config] 15 added, 0 changed, 0 removed
reading sources... [100%] user/social_login                                     
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] user/social_login                                      
generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [100%] images/freeradius_allowed_hosts.png                    
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in docs/build.
SUCCESS Crawled 129 urls in 3.82 seconds
./run-qa-checks: line 19:  6596 Terminated              python -m http.server 8001 -d docs/build/ &> /dev/null

Check JavaScript Linting

./openwisp_radius/static/openwisp-radius/js/mode-switcher.js is OK.

./openwisp_radius/static/openwisp-radius/js/radcheck.js is OK.

./openwisp_radius/static/openwisp-radius/js/strategy-switcher.js is OK.

Running checks for openwisp-radius
fatal: bad object 439b82b261e40d59854c2e45caf55794623f2bae
SUCCESS: Blank endline check successful!
SUCCESS: Migration name check on "./openwisp_radius/migrations" with migrations-to-ignore: 0 successful!
Skipped 1 files
SUCCESS: Isort check successful!
All done! ✨ 🍰 ✨
116 files would be left unchanged.
SUCCESS: Black check successful!
SUCCESS: Flake8 check successful!
Your commit message does not follow our commit message style guidelines:

- missing prefix in the commit short description
  Eg: "[feature/fix/change] Action performed"

Please read our guidelines at: http://openwisp.io/docs/developer/contributing.html#commit-message-style-guidelines
Checked commit message:


Merge 0de8f0c1d92d4f53b1f0d433d6b665ed4e9d28aa into 41b29d94a092f2d565f071983fdce9bdac84f335


ERROR: Commit message c [...]

2020-10-02 20:59 UTC, NoumbissiValere commented
@nemesisdesign I have reversed the implementation and tested it

2020-10-07 04:04 UTC, nemesisdesign requested changes
The admin field is missing:

![Screenshot from 2020-10-06 22-45-58](https://user-images.githubusercontent.com/841044/95285163-bc3f2880-0825-11eb-8966-3cda4e8d5a55.png)

Please add it and make sure it's listed after `sender`, it works as `freeradius_allowed_hosts` and try to replicate a test similar to `test_organization_radsettings_freeradius_allowed_hosts`.

See also my comments below.

2020-10-07 21:23 UTC, TravisBuddy commented
## Travis tests have failed

Hey @NoumbissiValere,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 4th Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-radius&#x2F;jobs&#x2F;733798300">View build log</a>


<details>
  <summary>
    <strong>
     .&#x2F;run-qa-checks
    </strong>
  </summary>

```
Checking documentation build status
Running Sphinx v3.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: [new config] 15 added, 0 changed, 0 removed
reading sources... [  6%] developer/contributing                                
reading sources... [ 13%] developer/freeradius                                  
reading sources... [ 20%] developer/how_to_extend                               
reading sources... [ 26%] developer/setup                                       
reading sources... [ 33%] general/goals                                         
reading sources... [ 40%] general/support                                       
reading sources... [ 46%] index                                                 
reading sources... [ 53%] user/api                                              
reading sources... [ 60%] user/enforcing_limits                                 
reading sources... [ 66%] user/generating_users                                 
reading sources... [ 73%] user/importing_users                                  
reading sources... [ 80%] user/management_commands                              
reading sources... [ 86%] user/registration                                     
reading sources... [ 93%] user/settings                                         
reading sources... [100%] user/social_login                                     


Warning, treated as error:
/home/travis/build/openwisp/openwisp-radius/docs/source/user/settings.rst:267:Error in "code-block" directive:
maximum 1 argument(s) allowed, 5 supplied.

.. code-block:: python
    OPENWISP_RADIUS_ALLOWED_MOBILE_PREFIXES = ['+44', '+237']
travis_time:end:1c8facda:start=1602105349756932941,finish=1602105351170428408,duration=1413495467,event=script
```

</details>


### 6th Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-radius&#x2F;jobs&#x2F;733798302">View build log</a>


<details>
  <summary>
    <strong>
     .&#x2F;run-qa-checks
    </strong>
  </summary>

```
Checking documentation build status
Running Sphinx v3.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: [new config] 15 added, 0 changed, 0 removed
reading sources... [100%] user/social_login                                     

Warning, treated as error:
/home/travis/build/openwisp/openwisp-radius/docs/source/user/settings.rst:267:Error in "code-block" directive:
maximum 1 argument(s) allowed, 5 supplied.

.. code-block:: python
    OPENWISP_RADIUS_ALLOWED_MOBILE_PREFIXES = ['+44', '+237']
```

</details>


###### TravisBuddy Request Identifier: 592de330-08e3-11eb-9b15-83942378e0dd

2020-10-08 02:32 UTC, nemesisdesign approved these changes
Good job Noumbissi, thanks! :+1: :clap:

2020-10-08 02:32 UTC, nemesisdesign commented on openwisp_radius/base/models.py
> +    'Comma separated list of international mobile prefixes to be restricted.'
Comma separated list of allowed international mobile prefixes.

2020-10-08 02:37 UTC, nemesisdesign approved these changes

2020-10-08 02:37 UTC, merged

2020-10-08 02:41 UTC, TravisBuddy commented
Hey @NoumbissiValere,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-radius&#x2F;builds&#x2F;733854102">View build log</a>

###### TravisBuddy Request Identifier: c0014440-090f-11eb-b9d6-41d4da7e5060