[deps] Migrate dependencie rest-auth to dj-rest-auth #168
openwisp/openwisp-radius pull request #172
Opened 2020-10-07 22:54 UTC by tullur

Django-rest-auth is not actively maintained, switched to the maintained fork dj-rest-auth.

2020-10-07 22:57 UTC, TravisBuddy commented
Hey @tullur,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-radius&#x2F;builds&#x2F;733820821">View build log</a>

###### TravisBuddy Request Identifier: 883e0030-08f0-11eb-9b15-83942378e0dd

2020-10-08 01:26 UTC, nemesisdesign requested changes
Thanks @tullur, see my comment below.

2020-10-08 01:26 UTC, nemesisdesign commented on requirements.txt
> +dj-rest-auth ~= 1.1.2
can you remove the spaces here please?

2020-10-08 10:14 UTC, tullur commented on requirements.txt
> +dj-rest-auth ~= 1.1.2
Yikes

2020-10-08 10:14 UTC, tullur commented on requirements.txt
> +dj-rest-auth ~= 1.1.2
Removed

2020-10-08 10:22 UTC, TravisBuddy commented
## Travis tests have failed

Hey @tullur,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 4th Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-radius&#x2F;jobs&#x2F;733931288">View build log</a>


<details>
  <summary>
    <strong>
     .&#x2F;run-qa-checks
    </strong>
  </summary>

```
Checking documentation build status
Running Sphinx v3.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: [new config] 15 added, 0 changed, 0 removed
reading sources... [  6%] developer/contributing                                
reading sources... [ 13%] developer/freeradius                                  
reading sources... [ 20%] developer/how_to_extend                               
reading sources... [ 26%] developer/setup                                       
reading sources... [ 33%] general/goals                                         
reading sources... [ 40%] general/support                                       
reading sources... [ 46%] index                                                 
reading sources... [ 53%] user/api                                              
reading sources... [ 60%] user/enforcing_limits                                 
reading sources... [ 66%] user/generating_users                                 
reading sources... [ 73%] user/importing_users                                  
reading sources... [ 80%] user/management_commands                              
reading sources... [ 86%] user/registration                                     
reading sources... [ 93%] user/settings                                         
reading sources... [100%] user/social_login                                     

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  6%] developer/contributing                                 
writing output... [ 13%] developer/freeradius                                   
writing output... [ 20%] developer/how_to_extend                                
writing output... [ 26%] developer/setup                                        
writing output... [ 33%] general/goals                                          
writing output... [ 40%] general/support                                        
writing output... [ 46%] index                                                  
writing output... [ 53%] user/api                                               
writing output... [ 60%] user/enforcing_limits                                  
writing output... [ 66%] user/generating_users                                  
writing output... [ 73%] user/importing_users                                   
writing output... [ 80%] user/management_commands                               
writing output... [ 86%] user/registration                                      
writing output... [ 93%] user/settings                                          
writing output... [100%] user/social_login                                      

generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [ 10%] images/demo_radius.gif                                 
copying images... [ 20%] images/swagger_api.png                                 
copying images... [ 30%] images/drf_api_interface.png                           
copying images... [ 40%] images/token.png                                       
copying images... [ 50%] images/org_uuid.png                                    
copying images... [ 60%] images/download_user_credentials_button.png            
copying images... [ 70%] images/pdf_of_user_list.png                            
copying images... [ 80%] images/add_users_prefix.gif                            
copying images... [ 90%] images/add_users_csv.gif                               
copying images... [100%] images/freeradius_allowed_hosts.png                    

copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in docs/build.
SUCCESS Crawled 129 urls in 3.86 seconds
./run-qa-checks: line 19:  6625 Terminated              python -m http.server 8001 -d docs/build/ &> /dev/null

Check JavaScript Linting

./openwisp_radius/static/openwisp-radius/js/mode-switcher.js is OK.

./openwisp_radius/static/openwisp-radius/js/radcheck.js is OK.

./openwisp_radius/static/openwisp-radius/js/strategy-switcher.js is OK.

Running checks for openwisp-radius
SUCCESS: Blank endline check successful!
SUCCESS: Migration name check on "./openwisp_radius/migrations" with migrations-to-ignore: 0 successful!
ERROR: /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/serializers.py Imports are incorrectly sorted and/or formatted.
--- /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/serializers.py:before	2020-10-08 10:15:41.198776
+++ /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/serializers.py:after	2020-10-08 10:16:41.459719
@@ -4,6 +4,12 @@
 import swapper
 from allauth.account.adapter import get_adapter
 from allauth.account.utils import setup_user_email
+from dj_rest_auth.registration.serializers import (
+    RegisterSerializer as BaseRegisterSerializer,
+)
+from dj_rest_auth.serializers import (
+    PasswordResetSerializer as BasePasswordResetSerializer,
+)
 from django.conf import settings
 from django.contrib.auth import get_user_model
 from django.contrib.auth.models import Group
@@ -12,10 +18,6 @@
 from django.utils import timezone
 from django.utils.translation import gettext_lazy as _
 from phonenumber_field.serializerfields import PhoneNumberField
-from dj_rest_auth.registration.serializers import (
-    RegisterSerializer as BaseRegisterSerializer,
-)
-from dj_rest_auth.serializers import PasswordResetSerializer as BasePasswordResetSerializer
 from rest_framework import serializers
 from rest_framework.exceptions import APIException
 
ERROR: /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/views.py Imports are incorrectly sorted and/or formatted.
--- /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/views.py:before	2020-10-08 10:15:41.198776
+++ /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/views.py:after	2020-10-08 10:16:41.483534
@@ -4,6 +4,12 @@
 import drf_link_header_pagination
 import swapper
 from allauth.account import app_settings as allauth_settings
+from dj_rest_auth import app_settings as rest_auth_settings
+from dj_rest_auth.app_settings import JWTSerializer, TokenSerializer
+from dj_rest_auth.registration.views import RegisterView as BaseRegisterView
+from dj_rest_auth.views import PasswordChangeView as BasePasswordChangeView
+from dj_rest_auth.views import PasswordResetConfirmView as BasePasswordResetConfirmView
+from dj_rest_auth.views import PasswordResetView as BasePasswordResetView
 from django.conf import settings
 from django.contrib.auth import get_user_model
 from django.contrib.auth.models import AnonymousUser
@@ -23,12 +29,6 @@
 from django_filters.rest_framework import DjangoFilterBackend
 from drf_yasg.utils import no_body, swagger_auto_schema
 from ipware import get_client_ip
-from dj_rest_auth import app_settings as rest_auth_settings
-from dj_rest_auth.app_settings import JWTSerializer, TokenSerializer
-from dj_rest_auth.registration.views import RegisterView as BaseRegisterView
-from dj_rest_auth.views import PasswordChangeView as BasePasswordChangeView
-from dj_rest_auth.views import PasswordResetConfirmView as BasePasswordResetConfirmView
-from dj_rest_auth.views import PasswordResetView as BasePasswordResetView
 from rest_framework import serializers, status
 from rest_framework.authentication import Bas [...]

2020-10-08 10:43 UTC, tullur commented
Test failed with:

`from rest_framework_simplejwt.serializers import TokenObtainPairSerializer`
`ModuleNotFoundError: No module named 'rest_framework_simplejwt'`

But if you add rest_framework_simplejwt module to the project and run tests, it would be failed:
 
`{'user': user, 'token': self.token}, context=context`
`AttributeError: 'RegisterView' object has no attribute 'token'`

2020-10-08 11:45 UTC, TravisBuddy commented
## Travis tests have failed

Hey @tullur,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 6th Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-radius&#x2F;jobs&#x2F;733947637">View build log</a>


<details>
  <summary>
    <strong>
     .&#x2F;run-qa-checks
    </strong>
  </summary>

```
Checking documentation build status
Running Sphinx v3.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: [new config] 15 added, 0 changed, 0 removed
reading sources... [100%] user/social_login                                     
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] user/social_login                                      
generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [100%] images/freeradius_allowed_hosts.png                    
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in docs/build.
SUCCESS Crawled 129 urls in 3.67 seconds
./run-qa-checks: line 19:  6576 Terminated              python -m http.server 8001 -d docs/build/ &> /dev/null

Check JavaScript Linting

./openwisp_radius/static/openwisp-radius/js/mode-switcher.js is OK.

./openwisp_radius/static/openwisp-radius/js/radcheck.js is OK.

./openwisp_radius/static/openwisp-radius/js/strategy-switcher.js is OK.

Running checks for openwisp-radius
SUCCESS: Blank endline check successful!
SUCCESS: Migration name check on "./openwisp_radius/migrations" with migrations-to-ignore: 0 successful!
ERROR: /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/serializers.py Imports are incorrectly sorted and/or formatted.
--- /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/serializers.py:before	2020-10-08 11:41:21.398518
+++ /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/serializers.py:after	2020-10-08 11:42:17.019526
@@ -4,6 +4,12 @@
 import swapper
 from allauth.account.adapter import get_adapter
 from allauth.account.utils import setup_user_email
+from dj_rest_auth.registration.serializers import (
+    RegisterSerializer as BaseRegisterSerializer,
+)
+from dj_rest_auth.serializers import (
+    PasswordResetSerializer as BasePasswordResetSerializer,
+)
 from django.conf import settings
 from django.contrib.auth import get_user_model
 from django.contrib.auth.models import Group
@@ -12,10 +18,6 @@
 from django.utils import timezone
 from django.utils.translation import gettext_lazy as _
 from phonenumber_field.serializerfields import PhoneNumberField
-from dj_rest_auth.registration.serializers import (
-    RegisterSerializer as BaseRegisterSerializer,
-)
-from dj_rest_auth.serializers import PasswordResetSerializer as BasePasswordResetSerializer
 from rest_framework import serializers
 from rest_framework.exceptions import APIException
 
ERROR: /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/views.py Imports are incorrectly sorted and/or formatted.
--- /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/views.py:before	2020-10-08 11:41:21.398518
+++ /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/views.py:after	2020-10-08 11:42:17.042888
@@ -4,6 +4,12 @@
 import drf_link_header_pagination
 import swapper
 from allauth.account import app_settings as allauth_settings
+from dj_rest_auth import app_settings as rest_auth_settings
+from dj_rest_auth.app_settings import JWTSerializer, TokenSerializer
+from dj_rest_auth.registration.views import RegisterView as BaseRegisterView
+from dj_rest_auth.views import PasswordChangeView as BasePasswordChangeView
+from dj_rest_auth.views import PasswordResetConfirmView as BasePasswordResetConfirmView
+from dj_rest_auth.views import PasswordResetView as BasePasswordResetView
 from django.conf import settings
 from django.contrib.auth import get_user_model
 from django.contrib.auth.models import AnonymousUser
@@ -23,12 +29,6 @@
 from django_filters.rest_framework import DjangoFilterBackend
 from drf_yasg.utils import no_body, swagger_auto_schema
 from ipware import get_client_ip
-from dj_rest_auth import app_settings as rest_auth_settings
-from dj_rest_auth.app_settings import JWTSerializer, TokenSerializer
-from dj_rest_auth.registration.views import RegisterView as BaseRegisterView
-from dj_rest_auth.views import PasswordChangeView as BasePasswordChangeView
-from dj_rest_auth.views import PasswordResetConfirmView as BasePasswordResetConfirmView
-from dj_rest_auth.views import PasswordResetView as BasePasswordResetView
 from rest_framework import serializers, status
 from rest_framework.authentication import BaseAuthentication, SessionAuthentication
 from rest_framework.authtoken.models import Token as UserToken
Skipped 1 files
ERROR: Isort check failed! Hint: did you forget running openwisp-qa-format?
--- openwisp_radius/api/serializers.py	2020-10-08 11:41:21.398518 +0000
+++ openwisp_radius/api/serializers.py	2020-10-08 11:42:18.048932 +0000
@@ -13,11 +13,13 @@
 from django.utils.translation import gettext_lazy as _
 from phonenumber_field.serializerfields import PhoneNumberField
 from dj_rest_auth.registration.serializers import (
     RegisterSerializer as BaseRegisterSerializer,
 )
-from dj_rest_auth.serializers import PasswordResetSerializer as BasePasswordResetSerializer
+from dj_rest_auth.serializers import (
+    PasswordResetSerializer as BasePasswordResetSerializer,
+)
 from rest_framework import serializers
 from rest_framework.exceptions import APIException
 
 from .. import settings as app_settings
 from ..utils import load_model
would reformat openwisp_radius/api/serializers.py
--- openwisp_radius/api/views.py	2020-10-08 11:41:21.398518 +0000
+++ openwisp_radius/api/views.py	2020-10-08 11:42:19.076082 +0000
@@ -535,12 +535,13 @@
         if getattr(settings, 'REST_USE_JWT', False):
             data = JWTSerializer(
                 {
                     'user': user,
                     'access_token': self.access_token,
-                    'refresh_token': self.refresh_token
-                }, context=context
+                    'refresh_token': self.refresh_token,
+                },
+                context=context,
             ).data
         else:
             data = TokenSerializer(user.auth_token, context=context).data
         radius_token = self.get_or_create_radius_token(
             user, self.organization, enable_auth=False
would reformat openwisp_radius/api/views.py
Oh no! 💥 💔 💥
2 files would be reformatted, 114 files would be left unchanged.
ERROR: Black check failed! Hint: did you forget running openwisp-qa-format?
./openwisp_radius/api/serializers.py:18:89: E501 line too long (91 > 88 characters)
./openwisp_radius/base/models.py:151:89: E501 line too long (110 > 88 characters)
ERROR: Flake8 check failed!
Your commit message does not follow our commit message style guidelines:

- You are mentioning an issue in the short description but it is not clear whether the issue is resolved or not;
  if it is resolved, please add to the commit long description:
  "Closes #<issue-number>" or "Fixes #<issue-number>";
  if the issue is not resolved yet, please use the following form:
  "Related to #<issue-number>"

Please read our guidelines at: http://openwisp.io/docs/developer/contributing.html#commit-message-style-guidelines
Checked commit message:


[deps] Migrate dependencie rest-auth to dj-rest-auth #168

django-rest-auth is not actively maintained, switched to the maintained fork dj-rest-auth


ERROR: Commit message check failed!
Migrations for 'openwisp_radius': openwisp_radius/migrations/0017_auto_20201008_0842.py - Alt [...]

2020-10-08 11:59 UTC, tullur commented
Hey @nemesisdesign , I fixed problem with token, dj-rest-auth replaced `rest_framework_jwt` with `django-rest-framework-simplejwt` (https://github.com/jazzband/dj-rest-auth/pull/3) and  now 'RegisterView' object has two attributes 'access_token' and 'refresh_token'

2020-10-08 12:02 UTC, TravisBuddy commented
## Travis tests have failed

Hey @tullur,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 6th Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-radius&#x2F;jobs&#x2F;733951224">View build log</a>


<details>
  <summary>
    <strong>
     .&#x2F;run-qa-checks
    </strong>
  </summary>

```
Checking documentation build status
Running Sphinx v3.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: [new config] 15 added, 0 changed, 0 removed
reading sources... [100%] user/social_login                                     
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] user/social_login                                      
generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [100%] images/freeradius_allowed_hosts.png                    
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in docs/build.
SUCCESS Crawled 129 urls in 3.60 seconds
./run-qa-checks: line 19:  6561 Terminated              python -m http.server 8001 -d docs/build/ &> /dev/null

Check JavaScript Linting

./openwisp_radius/static/openwisp-radius/js/mode-switcher.js is OK.

./openwisp_radius/static/openwisp-radius/js/radcheck.js is OK.

./openwisp_radius/static/openwisp-radius/js/strategy-switcher.js is OK.

Running checks for openwisp-radius
SUCCESS: Blank endline check successful!
SUCCESS: Migration name check on "./openwisp_radius/migrations" with migrations-to-ignore: 0 successful!
ERROR: /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/serializers.py Imports are incorrectly sorted and/or formatted.
--- /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/serializers.py:before	2020-10-08 11:58:28.743653
+++ /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/serializers.py:after	2020-10-08 11:59:23.141940
@@ -4,6 +4,12 @@
 import swapper
 from allauth.account.adapter import get_adapter
 from allauth.account.utils import setup_user_email
+from dj_rest_auth.registration.serializers import (
+    RegisterSerializer as BaseRegisterSerializer,
+)
+from dj_rest_auth.serializers import (
+    PasswordResetSerializer as BasePasswordResetSerializer,
+)
 from django.conf import settings
 from django.contrib.auth import get_user_model
 from django.contrib.auth.models import Group
@@ -12,10 +18,6 @@
 from django.utils import timezone
 from django.utils.translation import gettext_lazy as _
 from phonenumber_field.serializerfields import PhoneNumberField
-from dj_rest_auth.registration.serializers import (
-    RegisterSerializer as BaseRegisterSerializer,
-)
-from dj_rest_auth.serializers import PasswordResetSerializer as BasePasswordResetSerializer
 from rest_framework import serializers
 from rest_framework.exceptions import APIException
 
ERROR: /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/views.py Imports are incorrectly sorted and/or formatted.
--- /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/views.py:before	2020-10-08 11:58:28.743653
+++ /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/views.py:after	2020-10-08 11:59:23.164852
@@ -4,6 +4,12 @@
 import drf_link_header_pagination
 import swapper
 from allauth.account import app_settings as allauth_settings
+from dj_rest_auth import app_settings as rest_auth_settings
+from dj_rest_auth.app_settings import JWTSerializer, TokenSerializer
+from dj_rest_auth.registration.views import RegisterView as BaseRegisterView
+from dj_rest_auth.views import PasswordChangeView as BasePasswordChangeView
+from dj_rest_auth.views import PasswordResetConfirmView as BasePasswordResetConfirmView
+from dj_rest_auth.views import PasswordResetView as BasePasswordResetView
 from django.conf import settings
 from django.contrib.auth import get_user_model
 from django.contrib.auth.models import AnonymousUser
@@ -23,12 +29,6 @@
 from django_filters.rest_framework import DjangoFilterBackend
 from drf_yasg.utils import no_body, swagger_auto_schema
 from ipware import get_client_ip
-from dj_rest_auth import app_settings as rest_auth_settings
-from dj_rest_auth.app_settings import JWTSerializer, TokenSerializer
-from dj_rest_auth.registration.views import RegisterView as BaseRegisterView
-from dj_rest_auth.views import PasswordChangeView as BasePasswordChangeView
-from dj_rest_auth.views import PasswordResetConfirmView as BasePasswordResetConfirmView
-from dj_rest_auth.views import PasswordResetView as BasePasswordResetView
 from rest_framework import serializers, status
 from rest_framework.authentication import BaseAuthentication, SessionAuthentication
 from rest_framework.authtoken.models import Token as UserToken
Skipped 1 files
ERROR: Isort check failed! Hint: did you forget running openwisp-qa-format?
--- openwisp_radius/api/serializers.py	2020-10-08 11:58:28.743653 +0000
+++ openwisp_radius/api/serializers.py	2020-10-08 11:59:24.120887 +0000
@@ -13,11 +13,13 @@
 from django.utils.translation import gettext_lazy as _
 from phonenumber_field.serializerfields import PhoneNumberField
 from dj_rest_auth.registration.serializers import (
     RegisterSerializer as BaseRegisterSerializer,
 )
-from dj_rest_auth.serializers import PasswordResetSerializer as BasePasswordResetSerializer
+from dj_rest_auth.serializers import (
+    PasswordResetSerializer as BasePasswordResetSerializer,
+)
 from rest_framework import serializers
 from rest_framework.exceptions import APIException
 
 from .. import settings as app_settings
 from ..utils import load_model
would reformat openwisp_radius/api/serializers.py
--- openwisp_radius/api/views.py	2020-10-08 11:58:28.743653 +0000
+++ openwisp_radius/api/views.py	2020-10-08 11:59:25.143356 +0000
@@ -535,12 +535,13 @@
         if getattr(settings, 'REST_USE_JWT', False):
             data = JWTSerializer(
                 {
                     'user': user,
                     'access_token': self.access_token,
-                    'refresh_token': self.refresh_token
-                }, context=context
+                    'refresh_token': self.refresh_token,
+                },
+                context=context,
             ).data
         else:
             data = TokenSerializer(user.auth_token, context=context).data
         radius_token = self.get_or_create_radius_token(
             user, self.organization, enable_auth=False
would reformat openwisp_radius/api/views.py
Oh no! 💥 💔 💥
2 files would be reformatted, 114 files would be left unchanged.
ERROR: Black check failed! Hint: did you forget running openwisp-qa-format?
./openwisp_radius/api/serializers.py:18:89: E501 line too long (91 > 88 characters)
./openwisp_radius/base/models.py:151:89: E501 line too long (110 > 88 characters)
ERROR: Flake8 check failed!
Your commit message does not follow our commit message style guidelines:

- You are mentioning an issue in the short description but it is not clear whether the issue is resolved or not;
  if it is resolved, please add to the commit long description:
  "Closes #<issue-number>" or "Fixes #<issue-number>";
  if the issue is not resolved yet, please use the following form:
  "Related to #<issue-number>"

Please read our guidelines at: http://openwisp.io/docs/developer/contributing.html#commit-message-style-guidelines
Checked commit message:


[deps] Migrate dependencie rest-auth to dj-rest-auth #168

django-rest-auth is not actively maintained, switched to the maintained fork dj-rest-auth.
Update RegisterView JWTSerializer token to access_token and refresh_token and add django-rest-framework-simplejwt,
because dj-rest [...]

2020-10-09 11:10 UTC, TravisBuddy commented
## Travis tests have failed

Hey @tullur,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 3rd Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-radius&#x2F;jobs&#x2F;734255319">View build log</a>


<details>
  <summary>
    <strong>
     .&#x2F;run-qa-checks
    </strong>
  </summary>

```
Checking documentation build status
Running Sphinx v3.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: [new config] 15 added, 0 changed, 0 removed
reading sources... [  6%] developer/contributing                                
reading sources... [ 13%] developer/freeradius                                  
reading sources... [ 20%] developer/how_to_extend                               
reading sources... [ 26%] developer/setup                                       
reading sources... [ 33%] general/goals                                         
reading sources... [ 40%] general/support                                       
reading sources... [ 46%] index                                                 
reading sources... [ 53%] user/api                                              
reading sources... [ 60%] user/enforcing_limits                                 
reading sources... [ 66%] user/generating_users                                 
reading sources... [ 73%] user/importing_users                                  
reading sources... [ 80%] user/management_commands                              
reading sources... [ 86%] user/registration                                     
reading sources... [ 93%] user/settings                                         
reading sources... [100%] user/social_login                                     

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  6%] developer/contributing                                 
writing output... [ 13%] developer/freeradius                                   
writing output... [ 20%] developer/how_to_extend                                
writing output... [ 26%] developer/setup                                        
writing output... [ 33%] general/goals                                          
writing output... [ 40%] general/support                                        
writing output... [ 46%] index                                                  
writing output... [ 53%] user/api                                               
writing output... [ 60%] user/enforcing_limits                                  
writing output... [ 66%] user/generating_users                                  
writing output... [ 73%] user/importing_users                                   
writing output... [ 80%] user/management_commands                               
writing output... [ 86%] user/registration                                      
writing output... [ 93%] user/settings                                          
writing output... [100%] user/social_login                                      

generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [ 10%] images/demo_radius.gif                                 
copying images... [ 20%] images/swagger_api.png                                 
copying images... [ 30%] images/drf_api_interface.png                           
copying images... [ 40%] images/token.png                                       
copying images... [ 50%] images/org_uuid.png                                    
copying images... [ 60%] images/download_user_credentials_button.png            
copying images... [ 70%] images/pdf_of_user_list.png                            
copying images... [ 80%] images/add_users_prefix.gif                            
copying images... [ 90%] images/add_users_csv.gif                               
copying images... [100%] images/freeradius_allowed_hosts.png                    

copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in docs/build.

Check JavaScript Linting

./openwisp_radius/static/openwisp-radius/js/mode-switcher.js is OK.

./openwisp_radius/static/openwisp-radius/js/radcheck.js is OK.

./openwisp_radius/static/openwisp-radius/js/strategy-switcher.js is OK.

Running checks for openwisp-radius
SUCCESS: Blank endline check successful!
SUCCESS: Migration name check on "./openwisp_radius/migrations" with migrations-to-ignore: 0 successful!
ERROR: /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/serializers.py Imports are incorrectly sorted and/or formatted.
--- /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/serializers.py:before	2020-10-09 11:01:46.559109
+++ /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/serializers.py:after	2020-10-09 11:02:41.013197
@@ -4,6 +4,12 @@
 import swapper
 from allauth.account.adapter import get_adapter
 from allauth.account.utils import setup_user_email
+from dj_rest_auth.registration.serializers import (
+    RegisterSerializer as BaseRegisterSerializer,
+)
+from dj_rest_auth.serializers import (
+    PasswordResetSerializer as BasePasswordResetSerializer,
+)
 from django.conf import settings
 from django.contrib.auth import get_user_model
 from django.contrib.auth.models import Group
@@ -12,10 +18,6 @@
 from django.utils import timezone
 from django.utils.translation import gettext_lazy as _
 from phonenumber_field.serializerfields import PhoneNumberField
-from dj_rest_auth.registration.serializers import (
-    RegisterSerializer as BaseRegisterSerializer,
-)
-from dj_rest_auth.serializers import PasswordResetSerializer as BasePasswordResetSerializer
 from rest_framework import serializers
 from rest_framework.exceptions import APIException
 
ERROR: /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/views.py Imports are incorrectly sorted and/or formatted.
--- /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/views.py:before	2020-10-09 11:01:46.559109
+++ /home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/views.py:after	2020-10-09 11:02:41.037590
@@ -4,6 +4,12 @@
 import drf_link_header_pagination
 import swapper
 from allauth.account import app_settings as allauth_settings
+from dj_rest_auth import app_settings as rest_auth_settings
+from dj_rest_auth.app_settings import JWTSerializer, TokenSerializer
+from dj_rest_auth.registration.views import RegisterView as BaseRegisterView
+from dj_rest_auth.views import PasswordChangeView as BasePasswordChangeView
+from dj_rest_auth.views import PasswordResetConfirmView as BasePasswordResetConfirmView
+from dj_rest_auth.views import PasswordResetView as BasePasswordResetView
 from django.conf import settings
 from django.contrib.auth import get_user_model
 from django.contrib.auth.models import AnonymousUser
@@ -23,12 +29,6 @@
 from django_filters.rest_framework import DjangoFilterBackend
 from drf_yasg.utils import no_body, swagger_auto_schema
 from ipware import get_client_ip
-from dj_rest_auth import app_settings as rest_auth_settings
-from dj_rest_auth.app_settings import JWTSerializer, TokenSerializer
-from dj_rest_auth.registration.views import RegisterView as BaseRegisterView
-from dj_rest_auth.views import PasswordChangeView as BasePasswordChangeView
-from dj_rest_auth.views import PasswordResetConfirmView as BasePasswordResetConfirmView
-from dj_rest_auth.views import PasswordResetView as BasePasswordResetView
 from rest_framework import serializers, status
 from rest_framework.authentication import BaseAuthentication, SessionAuthentication
 from rest_framework.authtoken.models import Token as UserToken
Skipped 1 files
ERROR: Isort check failed! Hint:  [...]

2020-10-09 20:00 UTC, nemesisdesign requested changes
Can you rebase on the current master please?

Something like this:
```
git remote add upstream https://github.com/openwisp/openwisp-radius.git
git fetch upstream
git rebase upstream/master
```

Then, can you reformat the code with `openwisp-qa-format` please?

```
openwisp-qa-format
```

2020-10-09 21:23 UTC, tullur commented on requirements.txt
> +djangorestframework-simplejwt~=4.4.0
Yep

2020-10-09 22:30 UTC, TravisBuddy commented
## Travis tests have failed

Hey @tullur,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 6th Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-radius&#x2F;jobs&#x2F;734430523">View build log</a>


<details>
  <summary>
    <strong>
     coverage run --source&#x3D;openwisp_radius runtests.py
    </strong>
  </summary>

```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..................../home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/django/contrib/admin/options.py:801: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'openwisp_users.models.User'> QuerySet.
  return self.paginator(queryset, per_page, orphans, allow_empty_first_page)
./home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1370: RuntimeWarning: DateTimeField RadiusAccounting.start_time received a naive datetime (2017-06-10 10:50:00) while time zone support is active.
  RuntimeWarning)
/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1370: RuntimeWarning: DateTimeField RadiusAccounting.update_time received a naive datetime (2017-03-10 11:50:00) while time zone support is active.
  RuntimeWarning)
/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1370: RuntimeWarning: DateTimeField RadiusAccounting.stop_time received a naive datetime (2017-06-10 11:50:00) while time zone support is active.
  RuntimeWarning)
......Generated a batch of users with prefix test-prefix6
Generated a batch of users with prefix test-prefix6
Generated a batch of users with prefix test-prefix6
.........................Radius token does not exist. Obtain a new radius token or provide the organization UUID and API token.
..............Radius token does not exist. Obtain a new radius token or provide the organization UUID and API token.
...WARNING:root:No corresponding user found for username: admin
.WARNING:django.request:Forbidden: /api/v1/freeradius/accounting/
.WARNING:root:No corresponding user found for username: username
....WARNING:root:No corresponding user found for username: admin
..WARNING:root:No corresponding user found for username: admin
..WARNING:django.request:Unauthorized: /api/v1/test-org/radiusbatch/55cd2733-a18b-4142-bc0b-1c8cd1ec1321/pdf/
WARNING:django.request:Forbidden: /api/v1/test-org/radiusbatch/55cd2733-a18b-4142-bc0b-1c8cd1ec1321/pdf/
WARNING:django.request:Forbidden: /api/v1/test-org/radiusbatch/55cd2733-a18b-4142-bc0b-1c8cd1ec1321/pdf/
WARNING:django.request:Forbidden: /api/v1/test-org/radiusbatch/55cd2733-a18b-4142-bc0b-1c8cd1ec1321/pdf/
WARNING:django.request:Forbidden: /api/v1/test-org/radiusbatch/55cd2733-a18b-4142-bc0b-1c8cd1ec1321/pdf/
.WARNING:django.request:Bad Request: /api/v1/radiusbatch/
.WARNING:django.request:Not Found: /api/v1/random-valid-slug/account/password/change/
WARNING:openwisp_radius.api.views:User test_name1 is not member of organization test-org.
WARNING:django.request:Bad Request: /api/v1/test-org/account/password/change/
WARNING:django.request:Bad Request: /api/v1/test-org/account/password/change/
WARNING:django.request:Bad Request: /api/v1/test-org/account/token/
WARNING:django.request:Unauthorized: /api/v1/test-org/account/password/change/
.WARNING:django.request:Not Found: /api/v1/wrong-slug-name/account/password/reset/
WARNING:django.request:Bad Request: /api/v1/test-org/account/password/reset/
WARNING:django.request:Not Found: /api/v1/test-org/account/password/reset/
WARNING:openwisp_radius.api.views:User test_name1 is not member of organization test-org.
WARNING:django.request:Bad Request: /api/v1/test-org/account/password/reset/
WARNING:django.request:Bad Request: /api/v1/test-org/account/password/reset/confirm/
WARNING:django.request:Not Found: /api/v1/test-org/account/password/reset/confirm/
WARNING:django.request:Not Found: /api/v1/test-org/account/password/reset/confirm/
WARNING:django.request:Bad Request: /api/v1/test-org/account/token/
.WARNING:django.request:Method Not Allowed: /api/v1/test-org/account/password/reset/
....WARNING:django.request:Forbidden: /api/v1/freeradius/authorize/
WARNING:django.request:Forbidden: /api/v1/freeradius/authorize/
..WARNING:openwisp_radius.api.views:Radius token does not exist. Obtain a new radius token or provide the organization UUID and API token.
WARNING:django.request:Forbidden: /api/v1/freeradius/authorize/
.WARNING:openwisp_radius.api.views:username field is required.
WARNING:django.request:Forbidden: /api/v1/freeradius/authorize/
....WARNING:django.request:Bad Request: /api/v1/radiusbatch/
..WARNING:django.request:Not Found: /api/v1/test-org/radiusbatch/cf35ceb0-4c6b-4a2a-a1a7-6a26cc68b25f/pdf/
.....WARNING:django.request:Forbidden: /api/v1/test-org/radiusbatch/e3b6eb35-b74f-4eca-b430-36c3971e1c33/pdf/
.WARNING:django.request:Not Found: /api/v1/non-existent-org/radiusbatch/4e630c81-9d66-4d14-81eb-de56bea480d0/pdf/
.WARNING:django.request:Not Found: /api/v1/test-org/radiusbatch/00000000-0000-0000-0000-000000000000/pdf/
..WARNING:django.request:Method Not Allowed: /api/v1/freeradius/authorize/
.WARNING:django.request:Bad Request: /api/v1/freeradius/authorize/
.WARNING:django.request:Bad Request: /api/v1/freeradius/postauth/
.....WARNING:openwisp_radius.api.views:Radius token does not exist. Obtain a new radius token or provide the organization UUID and API token.
WARNING:django.request:Forbidden: /api/v1/freeradius/postauth/
.....WARNING:django.request:Unauthorized: /api/v1/radiusbatch/
WARNING:django.request:Forbidden: /api/v1/radiusbatch/
WARNING:django.request:Forbidden: /api/v1/radiusbatch/
WARNING:django.request:Forbidden: /api/v1/radiusbatch/
..WARNING:django.request:Not Found: /api/v1/00000000-0000-0000-0000-000000000000/account/
.ERROR:django.request:Internal Server Error: /api/v1/test-org/account/
.ERROR:django.request:Internal Server Error: /api/v1/test-org/account/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/travis/build/openwisp/openwisp-radius/openwisp_radius/api/views.py", line 424, in dispatch
    return super().dispatch(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/dj_rest_auth-1.1.2-py3.7.egg/dj_rest_auth/registration/views.py", line 43, in dispatch
    return super(RegisterView, self).dispatch(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/djangorestframework-3.11.2-py3.7.egg/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/djangorestframework-3.11.2-py3.7.egg/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  Fi [...]

2020-10-09 23:09 UTC, nemesisdesign approved these changes
Thanks @tullur!
I will finish to improve some details in the `dev` branch.
I found out the definition of the JWT requirement in dj-rest-auth is not usable via pip so we will have to redefine it but we can do so in the test settings.

2020-10-09 23:10 UTC, merged

2020-10-10 00:16 UTC, nemesisdesign commented
@tullur if you want to keep helping OpenWISP, please read [Help Us to Grow](https://openwisp.io/docs/general/help-us.html), it contains small pieces of advice which can help us a lot. Thank you.

2020-10-10 09:11 UTC, tullur commented
@nemesisdesign Ok, thank you for help and reviewing.