[refactor] Upgrade swapper #347
openwisp/openwisp-radius pull request #352
Opened 2021-11-17 16:10 UTC by yashikajotwani12

Fixes #347

2021-11-17 16:54 UTC, codesankalp requested changes
@yashikajotwani12 Many changes are not required see my suggestions below.
Also, update the swapper version:
https://github.com/openwisp/openwisp-radius/blob/b19de59455d40484674a2be870f99a2ee62568fe/setup.py#L39

2021-11-17 16:54 UTC, codesankalp commented on openwisp_radius/migrations/__init__.py
> +    return dependencies[0], '__latest__'
You don't have to repeat the whole code of swapper again, see my suggestions:

```suggestion
    def swappable_dependency_latest(value):
        return dependency(*value.split('.'), latest=True)
```

2021-11-17 16:54 UTC, codesankalp commented on openwisp_radius/migrations/__init__.py
> +    return is_swapped(app_label, model) or join(app_label, model)
```suggestion
```

2021-11-17 16:54 UTC, codesankalp commented on openwisp_radius/migrations/__init__.py
> +_prefixes = {}
```suggestion
```

2021-11-17 16:56 UTC, yashikajotwani12 commented
> @yashikajotwani12 Many changes are not required see my suggestions below. Also, update the swapper version:
> 
> https://github.com/openwisp/openwisp-radius/blob/b19de59455d40484674a2be870f99a2ee62568fe/setup.py#L39

Thanks! I would update these changes.

2021-11-18 05:04 UTC, codesankalp requested changes
@yashikajotwani12 Please test this locally i.e. `./run-qa-checks` and `./runtests` before pushing.

2021-11-18 05:04 UTC, codesankalp commented on openwisp_radius/migrations/__init__.py
> +        return dependency(*value.split('.'), latest=True)
```suggestion
    return dependency(*value.split('.'), latest=True)
 
```

2021-11-22 13:07 UTC, pandafy commented on openwisp_radius/migrations/__init__.py
> +    return dependency(*value.split('.'), latest=True)
I don't think we require this method anymore.

2021-11-22 13:13 UTC, pandafy requested changes
Following changes are required: 

```diff
diff --git a/openwisp_radius/migrations/0002_initial_openwisp_radius.py b/openwisp_radius/migrations/0002_initial_openwisp_radius.py
index 1cbfbbc..3f3e998 100644
--- a/openwisp_radius/migrations/0002_initial_openwisp_radius.py
+++ b/openwisp_radius/migrations/0002_initial_openwisp_radius.py
@@ -7,6 +7,7 @@ import django.core.validators
 import django.db.models.deletion
 import django.utils.timezone
 import model_utils.fields
+import swapper
 from django.conf import settings
 from django.db import migrations, models
 from swapper import get_model_name
@@ -14,10 +15,7 @@ from swapper import get_model_name
 import openwisp_users.mixins
 import openwisp_utils.base
 import openwisp_utils.utils
-from openwisp_radius.migrations import (
-    add_default_organization,
-    swappable_dependency_latest,
-)
+from openwisp_radius.migrations import add_default_organization
 
 
 class Migration(migrations.Migration):
@@ -31,7 +29,7 @@ class Migration(migrations.Migration):
     """
 
     dependencies = [
-        swappable_dependency_latest(settings.AUTH_USER_MODEL),
+        swapper.dependency(*settings.AUTH_USER_MODEL.split('.'), latest=True),
         ('openwisp_radius', '0001_initial_freeradius'),
     ]
 
diff --git a/openwisp_radius/migrations/__init__.py b/openwisp_radius/migrations/__init__.py
index 61fd7bd..bb9335a 100644
--- a/openwisp_radius/migrations/__init__.py
+++ b/openwisp_radius/migrations/__init__.py
@@ -146,7 +146,3 @@ def populate_phonetoken_phone_number(apps, schema_editor):
     for phone_token in PhoneToken.objects.all():
         phone_token.phone_number = phone_token.user.phone_number
         phone_token.save(update_fields=['phone_number'])
-
-
-def swappable_dependency_latest(value):
-    return (swappable_dependency(value)[0], '__latest__')
- ```

2021-11-22 13:15 UTC, pandafy commented on openwisp_radius/migrations/__init__.py
> +        return dependency(*value.split('.'), latest=True)
Do we still need this method?

2021-11-22 13:31 UTC, codesankalp commented
We can also use `swapper.split`

https://github.com/openwisp/django-swappable-models/blob/0f84196b65d316895d33a4eef28c7db86cb93ff5/swapper/__init__.py#L99-L101

2021-11-24 21:53 UTC, nemesisdesign requested changes
I think this line has to be updated to point to the new version:
https://github.com/openwisp/openwisp-radius/blob/master/setup.py#L39

The rest looks good.

@codesankalp what about improving `swapper.dependency` to allow passing a string which is split automatically like doing here (to avoid repeating this code in every module)?

2021-11-25 02:58 UTC, yashikajotwani12 commented
> I think this line has to be updated to point to the new version: https://github.com/openwisp/openwisp-radius/blob/master/setup.py#L39
> 
> The rest looks good.
> 
I have updated this.

2021-11-25 21:42 UTC, nemesisdesign reviewed
Looks good, I did one final improvement: https://github.com/openwisp/openwisp-radius/pull/352/commits/4586892295d53b1af87bc42599d55a8027251339.
Waiting for the build to finish before merging.

2021-11-25 21:51 UTC, nemesisdesign approved these changes
Thanks @yashikajotwani12 @codesankalp

2021-11-25 21:51 UTC, merged