[change] Exclude staff users from delete_unverified_users #353
openwisp/openwisp-radius pull request #354
Opened 2021-11-18 19:16 UTC by devkapilbansal

Closes #353

2021-11-19 01:21 UTC, nemesisdesign requested changes

2021-11-19 01:21 UTC, nemesisdesign commented on docs/source/user/management_commands.rst
> +Staff users will be excluded from the deletion process.
```suggestion
**Staff users will not be deleted by this management command.**
```

2021-11-19 01:21 UTC, nemesisdesign commented on openwisp_radius/tests/test_commands.py
> +                RadiusAccounting.objects.filter(username=opts['username']).exists(),
here I would change `opt['username']` to `user.username` to make this subtest block easier to read.

2021-11-22 12:59 UTC, pandafy requested changes

2021-11-22 12:59 UTC, pandafy commented on openwisp_radius/tests/test_commands.py
> +
```suggestion
        with self.subTest('Staff users should not be deleted'):
            _create_old_users()
            user = self._create_user(
                date_joined=now() - timedelta(days=3), is_staff=True
            )
            RegisteredUser.objects.create(
                user=user,
                method='email',
                is_verified=False,
            )
            self.assertEqual(User.objects.count(), 4)
            call_command(
                'delete_unverified_users',
            )
            self.assertEqual(User.objects.count(), 1)
            self.assertEqual(
                User.objects.filter(username=user.username, is_staff=True).exists(),
                True,
            )
```

2021-11-22 12:59 UTC, pandafy commented on openwisp_radius/tests/test_commands.py
> +            )
I believe this is added here by mistake.

2021-11-25 23:25 UTC, nemesisdesign commented on docs/source/user/management_commands.rst
> +**Staff users will not be deleted from this management command.**
```suggestion
**Staff users will not be deleted by this management command.**
```

2021-11-25 23:32 UTC, nemesisdesign approved these changes

2021-11-25 23:38 UTC, merged