[deps] Added support for django 3.2
openwisp/openwisp-radius pull request #357
Opened 2021-11-23 12:46 UTC by codesankalp

2021-11-23 12:50 UTC, codesankalp commented
For django 4.0 alpha, I am getting this:
```
  File "/home/sankalp/Desktop/openwisp/radius-venv/lib/python3.9/site-packages/organizations/abstract.py", line 30, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'
```
I think it needs deps update for django-organizations in openwisp-users.

2021-11-23 16:44 UTC, codesankalp commented
> For django 4.0 alpha, I am getting this:
> 
> ```
>   File "/home/sankalp/Desktop/openwisp/radius-venv/lib/python3.9/site-packages/organizations/abstract.py", line 30, in <module>
>     from django.utils.translation import ugettext_lazy as _
> ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'
> ```
> 
> I think it needs deps update for django-organizations in openwisp-users.

Now it is resolved.

2021-11-23 17:08 UTC, codesankalp commented
The django~=4.0rc1 build is failing due to the presence of `providing_args`:

https://github.com/stefanfoulis/django-sendsms/blob/75b4625dc444cea825363cec054f5c5e2b46c7ae/sendsms/signals.py#L4

And the `django-sendsms` repo seems to be inactive.

2021-11-24 14:00 UTC, codesankalp commented
The tests are now failing due to:

![image](https://user-images.githubusercontent.com/56037184/143248639-b5996612-b2eb-48b4-8fd3-4b4b289c8500.png)

which is due to

https://github.com/django/django/commit/354bbf1fd22cd0a826e8da75ba16bc28fc274868

and

https://github.com/axnsan12/drf-yasg/blob/effc8f2c06e66813a0ab5bad5a4478c0a8e1969c/src/drf_yasg/utils.py#L186

Should I create an issue in `drf-yasg`?

2021-11-24 14:25 UTC, pandafy commented
> Should I create an issue in `drf-yasg`?

Looking at drf-yasg test environment, I don't think they support Django 4 at the moment. 

https://github.com/axnsan12/drf-yasg/blob/effc8f2c06e66813a0ab5bad5a4478c0a8e1969c/tox.ini#L22-L42

2021-11-25 22:01 UTC, nemesisdesign commented on setup.py
> +        'django>=3.0,<=4.0rc1',
What about:
```suggestion
        'django>=3.0.0,<4.1.0',
```
So that we include later versions of Django 4 once released?

2021-11-26 19:45 UTC, nemesisdesign requested changes

2021-11-26 19:45 UTC, nemesisdesign commented on setup.py
> +        'django-sendsms @ https://github.com/codesankalp/django-sendsms/tarball/master',
this can be updated to point to the main repo

2021-11-26 19:45 UTC, nemesisdesign commented on tests/openwisp2/sample_users/models.py
> +        abstract = True
let's be consistent with what done in the other PRs

2021-11-26 19:45 UTC, nemesisdesign commented on setup.py
> +            'tarball/issue-292-deps-django-supports'
I think we can point to master now

2022-01-12 21:59 UTC, nemesisdesign approved these changes

2022-01-12 22:00 UTC, merged