[Fix] csv api endpoint path
openwisp/openwisp-radius pull request #376
Opened 2022-02-04 17:11 UTC by dishantsethi

The CSV row is redirecting to radiusbatch/csv/<uuid>.csv which is an incorrect URL.
Instead, it should be /api/v1/radiusbatch/csv/<uuid>.csv
<img width="591" alt="Screenshot 2022-02-04 at 10 26 30 PM" src="https://user-images.githubusercontent.com/31399916/152572222-f36ead04-5721-40bd-882a-0e07082217de.png">
<img width="885" alt="Screenshot 2022-02-04 at 10 29 02 PM" src="https://user-images.githubusercontent.com/31399916/152572258-cbc46523-0f50-484c-9cb0-9fb1c17f3657.png">

2022-02-06 10:00 UTC, dishantsethi commented
Changed Download batch CSV API endpoint from ```radiusbatch/csv/<uuid>/filename.csv``` to ```radius/organization/<slug:slug>/batch/<uuid:pk>/csv/filename.csv``` maintain consistency.

@nemesisdesign @atb00ker  Review Required!

I'll be adding this is swagger API docs post review.

2022-02-08 18:20 UTC, atb00ker reviewed
Minor problem, see below.
The rest seems good! 😄

2022-02-08 18:20 UTC, atb00ker commented on docs/source/user/api.rst
> +id               string
Please check spacing. (tab or spaces) here.

2022-02-08 18:32 UTC, dishantsethi commented
@atb00ker Fixed!

2022-02-08 20:57 UTC, Aryamanz29 commented
> @atb00ker Fixed!

Please run following commands on terminal :

QA commands 👇
```bash
openwisp-qa-format
./run-qa-checks
```
Test commands :point_down: 
```bash
coverage run --source=openwisp_radius runtests.py
SAMPLE_APP=1 ./runtests.py --parallel --keepdb
```
Also follow `openwisp commit message guidelines` : http://openwisp.io/docs/developer/contributing.html#commit-message-style-guidelines

2022-02-09 05:08 UTC, codesankalp requested changes

2022-02-09 05:08 UTC, codesankalp commented on openwisp_radius/settings.py
> +CSV_URL_PATH = 'api/v1/radius/organisation/'
For consistency:
```suggestion
CSV_URL_PATH = 'api/v1/radius/organization/'
```

2022-02-10 15:08 UTC, dishantsethi commented
Hi @atb00ker @codesankalp 
Made the necessary changes and ran tests locally. Let me know if anything is left.

2022-02-10 17:09 UTC, atb00ker reviewed
Hey commit guide is still wrong, 
Was `openwisp-qa-checks` passing on your local? (That might be some setup issue!)

To fix it, do:
```
$ git commit --amend
#
[change] Update download batch CSV URL and add in API docs #373

Closes #373
```

2022-02-10 17:13 UTC, dishantsethi commented
Updated the commit message. @atb00ker

2022-02-10 17:31 UTC, atb00ker submitted a review, later dismissed

2022-03-08 18:51 UTC, nemesisdesign approved these changes
Thanks :+1:

2022-03-08 18:59 UTC, merged