[Fix] Made private storage backend configuration #417
openwisp/openwisp-radius pull request #419
Opened 2022-06-13 17:10 UTC by codesankalp

Fixes #417

2022-06-14 19:54 UTC, nemesisdesign requested changes
One suggestion below.

@pandafy WDT?

2022-06-14 19:54 UTC, nemesisdesign commented on docs/source/user/settings.rst
> +This instance is used for storing csv files to batch import users.
```suggestion
This instance is used for storing csv files of batch imports of users.
```

2022-06-15 08:34 UTC, pandafy submitted a review, later dismissed
The code looks good. I have also did a manual test.

2022-06-15 19:40 UTC, nemesisdesign approved these changes

2022-06-15 19:40 UTC, merged