[feature] Added setting to customize SMS message #432
openwisp/openwisp-radius pull request #433
Opened 2022-08-30 13:05 UTC by pandafy

Closes #432

2022-09-01 10:17 UTC, nemesisdesign requested changes
There's a detail regarding the translation of the text which is not clear so I am suggesting to amend the docs.

Here's one problems I found during testing that seem related to the fallback field.
Please can you double check these issues? If confirmed please create a new issue for this.

If I delete the sms message entirely and save, I expect the fallback value to be used and shown, but that's not the case, I think it's because the value saved to the DB is an empty string. I guess that when the value of the text field is falsy we shall set it to `None` automatically.

The rest is good.

2022-09-01 10:17 UTC, nemesisdesign commented on docs/source/user/settings.rst
> +it from organization change page for each organization.
I would add another bit of text to explain the following:
```
Keep in mind that the default value is translated in other languages, If the value is customized the translations will not work, so if you need this message to be translated in different languages you should either not change the default value or prepare the additional translations.
```

Please can you double check to ensure the translation continues working also after this change?

2022-09-01 10:17 UTC, nemesisdesign commented on docs/source/user/settings.rst
> +**Default**: ``{organization_name} verification code: {code}``
You changed the string and broke the translations.

```
from django.utils.translation import gettext as _
from django.utils.translation import activate, get_language_info
activate("it")
_(org.radius_settings.sms_message)
 '{organization_name} verification code: {code}'
```

Why did you change `{organization}` to `{organization_name}`?
**That is a backward incompatible change.**

2022-09-01 14:55 UTC, pandafy commented
> Here's one problems I found during testing that seem related to the fallback field.
> Please can you double check these issues? If confirmed please create a new issue for this.

I can replicate this issue locally. I have opened https://github.com/openwisp/openwisp-radius/issues/435

2022-09-05 19:10 UTC, nemesisdesign commented on openwisp_radius/base/models.py
> +            self.sms_message = None
isn't this slightly redundant with https://github.com/openwisp/openwisp-radius/pull/436?

2022-09-09 08:33 UTC, nemesisdesign approved these changes

2022-09-09 08:34 UTC, merged